# Generated by Django 5.1.4 on 2025-02-20 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('key', models.CharField(blank=True, max_length=8, unique=True)),
                ('industry', models.CharField(choices=[('IT', 'IT'), ('Marketing', 'Marketing'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Other', 'Other')], default='Other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=10, verbose_name='Role')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_project_users',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='projects', through='project.ProjectUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='projectuser',
            index=models.Index(fields=['project'], name='project_pro_project_baff88_idx'),
        ),
        migrations.AddIndex(
            model_name='projectuser',
            index=models.Index(fields=['user'], name='project_pro_user_id_ee0ded_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectuser',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project'),
        ),
    ]
