# Generated by Django 5.1.4 on 2025-02-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('key', models.CharField(blank=True, max_length=8, unique=True)),
                ('industry', models.CharField(choices=[('IT', 'IT'), ('Marketing', 'Marketing'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Other', 'Other')], default='Other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=10, verbose_name='Role')),
            ],
            options={
                'db_table': 'project_project_users',
            },
        ),
    ]
