# Generated by Django 5.1.4 on 2025-02-16 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users', to='project.project'),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='projects', through='project.ProjectUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='projectuser',
            index=models.Index(fields=['project'], name='project_pro_project_baff88_idx'),
        ),
        migrations.AddIndex(
            model_name='projectuser',
            index=models.Index(fields=['user'], name='project_pro_user_id_ee0ded_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectuser',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project'),
        ),
    ]
