# Generated by Django 5.1.4 on 2025-02-16 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='admin_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
