# Generated by Django 5.1.4 on 2025-03-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projectuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True),
        ),
    ]
