# Generated by Django 5.1.4 on 2025-04-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_name_alter_projectuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='role',
            field=models.CharField(choices=[('member', 'Member')], default='member', max_length=10, verbose_name='Role'),
        ),
    ]
