# Generated by Django 5.2.1 on 2025-05-17 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0005_alter_projectuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('core_review', 'Core Review'), ('done', 'Done')], default='to_do', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('task_type', models.CharField(choices=[('task', 'Task'), ('bug', 'Bug'), ('story', 'Story')], default='task', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'status', 'order'],
                'indexes': [models.Index(fields=['project', 'status', 'order'], name='task_task_project_9759a2_idx'), models.Index(fields=['assignee'], name='task_task_assigne_8f7780_idx'), models.Index(fields=['reporter'], name='task_task_reporte_dfac24_idx'), models.Index(fields=['due_date'], name='task_task_due_dat_c36b93_idx'), models.Index(fields=['priority'], name='task_task_priorit_21ce1f_idx'), models.Index(fields=['task_type'], name='task_task_task_ty_56e246_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'status', 'order'), name='unique_task_order_per_project_status')],
            },
        ),
    ]
