# Generated by Django 5.1.4 on 2025-05-03 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_projectuser_role'),
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_order_per_status',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_task_project_104291_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_task_status_5e4c6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_task_order_d7d748_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='The user assigned to work on this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the task.', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='The date when the task is expected to be completed.', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='The name or title of the task.', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The order of the task within its status column for a specific project.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(help_text='The project this task belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reporter',
            field=models.ForeignKey(help_text='The user who created or reported this task.', on_delete=django.db.models.deletion.CASCADE, related_name='reported_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('core_review', 'Core Review'), ('done', 'Done')], db_index=True, default='to_do', help_text='The current status of the task.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status', 'order'], name='task_task_project_9759a2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee'], name='task_task_assigne_8f7780_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['reporter'], name='task_task_reporte_dfac24_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='task_task_due_dat_c36b93_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('project', 'status', 'order'), name='unique_task_order_per_project_status'),
        ),
    ]
