# Generated by Django 5.1.4 on 2025-05-03 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_projectuser_role'),
        ('task', '0002_remove_task_unique_task_order_per_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', help_text='The priority level of the task.', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('task', 'Task'), ('bug', 'Bug'), ('story', 'Story')], db_index=True, default='task', help_text='The type of the task (e.g., Task, Bug, Story).', max_length=10),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='task_task_priorit_21ce1f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type'], name='task_task_task_ty_56e246_idx'),
        ),
    ]
